import { Message } from '../../types/message.type';

export const allMessages: Message[] = [
  {
    customer_id: 1,
    msg_subject: 'Welcome to BIG Bank',
    msg_status: 'Open',
    msg_body:
      'Dear Julian Golovens,\n\nWelcome to BIG bank, and thank you for opening a new account with us.\n\nWe’re delighted to have you join us, and as a small token of our appreciation, we have credited £200 to your account.\n\nIf you have any questions or need assistance, our team is always here to help.\n\nThank you for choosing us.\n\nKind regards,\nYour Bank Team.',
    msg_created_by: 'autogenerated',
    is_read: false,
  },
  {
    customer_id: 1,
    msg_subject: 'Loan Application',
    msg_status: 'Open',
    msg_body:
      'If you are considering applying for a personal loan, our team is here to help guide you through the process. We understand that financial decisions are important, and we aim to provide clear, supportive information tailored to your needs.\n\nOur loan department can offer detailed advice on available options, eligibility requirements, and repayment plans. Whether you’re planning a major purchase, consolidating debt, or covering unexpected expenses, we’re ready to assist you in finding the most suitable solution.\n\nPlease don’t hesitate to contact our loan department for more information. Our representatives will be happy to answer your questions and help you take the next step with confidence.',
    msg_created_by: 'Sam',
    is_read: false,
  },
  {
    customer_id: 1,
    msg_subject: 'Card Replacement',
    msg_status: 'Open',
    msg_body:
      'We have received your request to replace your debit card. \n\nPlease allow 5-7 business days for processing.',
    msg_created_by: 'Sam',
    is_read: false,
  },
  {
    customer_id: 2,
    msg_subject: 'Welcome to BIG Bank',
    msg_status: 'Open',
    msg_body:
      'Dear Tom Simpsons,\n\nWelcome to BIG bank, and thank you for opening a new account with us.\n\nWe’re delighted to have you join us, and as a small token of our appreciation, we have credited £200 to your account.\n\nIf you have any questions or need assistance, our team is always here to help.\n\nThank you for choosing us.\n\nKind regards,\nYour Bank Team.',
    msg_created_by: 'autogenerated',
    is_read: false,
  },
];
