export const mockUsersService = {
  findAll: jest.fn().mockReturnValue([
    {
      customer_id: 1,
      first_name: 'Julian',
      last_name: 'Golovens',
      email: 'julian@test.com',
      phone: '123-456-7890',
      customer_address: '123 Main St, Springfield, IL',
      dob: '1995-06-15',
      phone_verified: false,
      email_verified: false,
      created_at: '2026-04-20 20:53:22',
    },
    {
      customer_id: 2,
      first_name: 'Tom',
      last_name: 'Simpsons',
      email: 'tomSimpson@gmail.com',
      phone: '123-456-7890',
      customer_address: '456 Main St, Springfield, IL',
      dob: '1985-06-15',
      phone_verified: false,
      email_verified: false,
      created_at: '2025-04-20 20:53:22',
    },
  ]),

  findOne: jest.fn().mockReturnValue({
    customer_id: 1,
    first_name: 'Julian',
    last_name: 'Golovens',
    email: 'julian@test.com',
    phone: '123-456-7890',
    customer_address: '123 Main St, Springfield, IL',
    dob: '1995-06-15',
    phone_verified: false,
    email_verified: false,
    created_at: '2026-04-20 20:53:22',
  }),

  create: jest.fn().mockReturnValue({
    customer_id: 3,
    first_name: 'Bill',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    phone: '123456789',
    customer_address: 'Manchester, UK',
    dob: '1990-01-01',
    phone_verified: false,
    email_verified: false,
    created_at: '2026-04-20 20:53:22',
  }),

  update: jest.fn().mockReturnValue({
    customer_id: 3,
    first_name: 'Bill',
    last_name: 'McDoe',
    email: 'john.doe@example.com',
    phone: '123456789',
    customer_address: 'Manchester, UK',
    dob: '1990-01-01',
    phone_verified: false,
    email_verified: false,
    created_at: '2026-04-20 20:53:22',
  }),

  remove: jest.fn().mockReturnValue('User removed successfully'),
};
