import type { Metadata } from "next";
import { AdminProvider } from "./AdminContext"; //To provide global state, Context
import { redirect } from "next/navigation";
import { loadAdmin } from "../actions/auth-admin";

export const metadata: Metadata = {
  title: "Admin Bank login",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let admin = null;

  try {
    admin = await loadAdmin();
  } catch {
    redirect("/login");
  }

  return <AdminProvider initialAdmin={admin}>{children}</AdminProvider>;
}
