import type { Metadata } from "next";
import { UserProvider } from "./UserContext"; //To provide global state, Context
import { loadUser } from "../actions/auth-server";
import { redirect } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import { loadUserAllAccounts } from "../actions/loadUserAccounts";
import { loadUserAllTransactions } from "../actions/loadUserAllTransactions";

export const metadata: Metadata = {
  title: "User Bank login",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let activeUser = null;
  let userAllAccounts = null;
  let userAllTransactions = null;

  try {
    activeUser = await loadUser();
    userAllAccounts = await loadUserAllAccounts();
    userAllTransactions = await loadUserAllTransactions();
  } catch {
    redirect("/login");
  }

  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <UserProvider
        initialUser={activeUser}
        initialUserAllAccounts={userAllAccounts}
        initialUserAllTransactions={userAllTransactions}
      >
        {children}
      </UserProvider>
    </div>
  );
}
