import type { Metadata } from "next";
import { UserProvider } from "./UserContext"; //To provide global state, Context
import { loadUser } from "../actions/auth-server";
import { redirect } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import { loadUserAllAccounts } from "../actions/loadUserAccounts";

export const metadata: Metadata = {
  title: "User Bank login",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let activeUser = null;
  let userAllAccounts = null;

  try {
    activeUser = await loadUser();
    userAllAccounts = await loadUserAllAccounts();
  } catch {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider
          initialUser={activeUser}
          initialUserAllAccounts={userAllAccounts}
        >
          {children}
        </UserProvider>
        ;
      </body>
    </html>
  );
}
