export const mockTransactionsService = {
  findAll: jest.fn().mockReturnValue([
    {
      transaction_id: 1,
      account_id: 1,
      customer_id: 1,
      money_amount: +2000.0,
      balance: 3000.0,
      details: 'Initial deposit',
    },
    {
      transaction_id: 2,
      account_id: 1,
      customer_id: 1,
      money_amount: -500.0,
      balance: 2500.0,
      details: 'ATM Withdrawal',
    },
    {
      transaction_id: 3,
      account_id: 1,
      customer_id: 1,
      money_amount: -4.5,
      balance: 2495.5,
      details: 'Tesco Superstore',
    },
  ]),

  getAllTransactions: jest.fn().mockReturnValue([
    {
      transaction_id: 1,
      account_id: 1,
      customer_id: 1,
      money_amount: +2000.0,
      balance: 3000.0,
      details: 'Initial deposit',
      transaction_date: '2026-04-13T18:40:52.194Z',
      first_name: 'Julian',
      last_name: 'Golovens',
      email: 'julian@test.com',
      phone: '123-456-7890',
      customer_address: '123 Main St, Springfield, IL',
      dob: '1995-06-15T00:00:00.000Z',
      account_type: 'Main',
    },
    {
      transaction_id: 2,
      account_id: 1,
      customer_id: 1,
      money_amount: -500.0,
      balance: 2500.0,
      details: 'ATM Withdrawal',
      transaction_date: '2026-04-13T18:40:52.196Z',
      first_name: 'Julian',
      last_name: 'Golovens',
      email: 'julian@test.com',
      phone: '123-456-7890',
      customer_address: '123 Main St, Springfield, IL',
      dob: '1995-06-15T00:00:00.000Z',
      account_type: 'Main',
    },
  ]),

  findOne: jest.fn().mockReturnValue({
    transaction_id: 1,
    account_id: 1,
    customer_id: 1,
    money_amount: +2000.0,
    balance: 3000.0,
    details: 'Initial deposit',
  }),

  findCurrentUserAllTrx: jest.fn().mockReturnValue([
    {
      transaction_id: 1,
      account_id: 1,
      customer_id: 1,
      money_amount: +2000.0,
      balance: 3000.0,
      details: 'Initial deposit',
    },
    {
      transaction_id: 2,
      account_id: 1,
      customer_id: 1,
      money_amount: -500.0,
      balance: 2500.0,
      details: 'ATM Withdrawal',
    },
    {
      transaction_id: 3,
      account_id: 1,
      customer_id: 1,
      money_amount: -4.5,
      balance: 2495.5,
      details: 'Tesco Superstore',
    },
  ]),

  create: jest.fn().mockReturnValue({
    transaction_id: 26,
    account_id: 1,
    customer_id: 1,
    money_amount: +100.0,
    balance: 100.0,
    details: 'test statement',
  }),

  update: jest.fn().mockReturnValue({
    transaction_id: 3,
    account_id: 1,
    customer_id: 1,
    money_amount: -4.5,
    balance: 2495.5,
    details: 'ASDA Shopping',
  }),

  remove: jest.fn().mockReturnValue('Transaction deleted successfully'),
};
